// ── 공유 상태 객체 (모든 모듈 공유) ──
const S = window.S = {
  entries:{}, projects:{}, calEvents:{}, memos:{}, comments:{}, userAlerts:{},
  filterTag:'전체', editId:null, projSortOrder:'asc', teamFilter:'전체',
  calTeamFilters:new Set(['전체']), calMemberFilter:'',
  schTeamFilters:new Set(['전체']), schMemberFilter:'',
  ganttTeamFilter:'전체', memoPersonFilter:'전체', memoGroupFilter:'전체',
  calView:'work',
  calYear:new Date().getFullYear(), calMonth:new Date().getMonth(),
  viewDate:new Date().toISOString().slice(0,10),
  _memberListCache:JSON.parse(localStorage.getItem('memberList')||'["방준수","김유빈","이지훈","박서연","최민준"]'),
  _pinDataCache:JSON.parse(localStorage.getItem('pinData')||'{}'),
  _groupsCache:JSON.parse(localStorage.getItem('groupsData')||'{}'),
  _favCache:{},
  historyData:{}, _progLogCache:{},
  _pinBuffer:'', _pinTargetUser:'', _pinMode:'login', _pinOldVerified:'',
  _adminPinBuf:'', _adminEditTarget:'', _adminEditBuf:'', _adminTab:'pin',
  _promptCallback:null, _cpTarget:'', _cpOldBuf:'', _cpNewBuf:'', _alBuf:'',
  _prevEntryKeys:null, _prevHistorySnap:{}, _notifyEnabled:localStorage.getItem('notifyEnabled')!=='false',
  _dndMode:false, _callTargetName:'', _callTargetGroup:'', _incomingCallId:'',
  _dndCache:{}, _absenceCache:{}, _lastMouseMove:Date.now(), _memberStatusCache:{},
  _userInitDone:false, _timerInterval:null, _timerStart:null, _calEventDate:'',
  _ganttCellEditSchId:'', _ganttCellEditDate:'',
  _cmpYear:new Date().getFullYear(), _bdpYear:new Date().getFullYear(), _bdpMonth:new Date().getMonth(),
};
